### ISSUE TITLE
Sending params along with time_entries GET request

### ISSUE THREAD

**Issue by chrisphilton** [Yaaqoub/node-harvest-v2#1]
Hey @Yaaqoub,

How would I pass along parameters along with the `time_entries` GET request? the Harvest API allows for parameters to narrow to the `list` results for various objects.

Thanks!

**Comment by Yaaqoub** [comment]
Hello @chrisphilton 

I didn't really understand your question can you explain exactly what you want.

To create a time entry, that's an example : 
`harvest.timeEntries.create({
    "project_id": "16195969",
    "task_id": "8936519",
    "spent_date": "2018-01-19"
}, function(error, response, res) {
    if (!error) {
        console.log(res);
    }
});`

Kind regard!

**Comment by dgibney** [comment]
First off thanks for creating and publishing this library. I also have hit the same roadblock encountered by @chrisphilton. 

As per [harvest API documentation](https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/) you can filter and page the time entries; 

So say I want to get all time entries for a given day I'd pass the **from** and **to** querystring params; time_entries?from=2018-01-23&to=2018-01-23&page=1&pagesize=100.

Suggested updates;

**time_entries.js;**

```
    list(qs, cb) {
        this.options.url = this.baseUri;
        this.options.qs = qs;

        new Request(this.options, cb);
    }
```
You'd consume this as follows;

```
            harvest.timeEntries.list({from:dateFrom, to: dateFrom, page:1, per_page:100}, function(error, response, results){
                let json = JSON.parse(results);
                timeEntries = json.time_entries;

                console.log(timeEntries.length);
            });
```

This update would need to be made for all list calls;

- Clients
- Client Contacts
- Invoices
- Invoice Messages
- Invoice Payments
- Invoice Item Categories
- Invoice Line Item
- Estimates
- Estimate Messages
- Estimate Item Categories
- Expenses
- Expense Categories
- Tasks
- Time Entries
- Projects
- Project User Assignments
- Project Task Assignments
- Roles
- Users
- User Project Assignments

Happy to create a pull request.

**Comment by Yaaqoub** [comment]
Hello,
I will create a fix for this soon, it will be good if you contribute to the project.

**Comment by Yaaqoub** [comment]
Hello @dgibney @chrisphilton,

I created a fix for that issue (I am sorry for being late). now there is two methods for timeEntries 'list' and 'listAll'.

- [Time Entries](https://help.getharvest.com/api-v2/timesheets-api/timesheets/time-entries/)
    - `list({params}, callback)`
    - `listAll(callback)`
    - `retrieve(timeEntryID, callback)`
    - `create({params}, callback)`
    - `update(timeEntryID, {params}, callback)`
    - `delete(timeEntryID, callback)`
    - `restart(timeEntryID, callback)`
    - `stop(timeEntryID, callback)`
    - `Example: `
        ```js
        harvest.timeEntries.list()
        ```

In your case you can do this now:

```js
harvest.timeEntries.listAll(function(error, response, res) {
    if (!error) {
        console.log(res);
    }
});
```
Or
```js
harvest.timeEntries.list({
    from:'2018-02-07', 
    to: '2018-02-09', 
    page:1, 
    per_page:100
}, function(error, response, res) {
    if (!error) {
        console.log(res);
    }
});
```
Kind regards.

**Comment by sdlaursen** [comment]
Any news on implementing this on all the other "list" calls. I need this as well? I'm not an experienced nodejs developer (yet), so I won't infect your project with my own bad attempts at implementing it.. But locally I have implemented it for /invoices list and it works perfectly.

**Comment by Yaaqoub** [comment]
Hello @sdlaursen,
we change the project structure, so the new one has some errors I will fix it soon, so we look into that.
