### ISSUE TITLE
harvest.projectTaskAssignments.list returns 404 and HTML

### ISSUE THREAD

**Issue by thetwosents** [Yaaqoub/node-harvest-v2#5]
When I call the projectTaskAssignments with my projectID as documented, returns:

`<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="Pragma" content="no-cache" />\n  <title>HARVEST: Canʼt find page</title>\n  <script>\n    <!--\n\n    var accounturl = null;\n\n    function url_test() {\n      accounturl = window.location.href.substr(0, window.location.href.search(/\\.com/)+4);\n      if(window.location.port) accounturl += ":" + window.location.port;\n      accounturl += "/";\n\n      var host = window.location.hostname;\n      var wwwexp = /www/;\n\n      if(!wwwexp.test(host)){\n        var re = new RegExp(/^([^.]+)\\..*$/);\n        var m = re.exec(host);\n        if (m != null && m[1]!="www" && m[1]!="localhost"){\n          document.getElementById(\'account404\').style.display = \'list-item\';\n          document.getElementById(\'market404\').style.display = \'none\';\n        }\n      }\n    }\n\n    // End -->\n  </script>\n  <style type="text/css">\n    body {\n      font: 12px/16px "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;\n      background:#e7e7e7;\n      color: #333;\n    }\n\n    a {color: #F60;}\n    a:hover { color: #F60; text-decoration: none;}\n\n    div#header {height:36px; border-bottom: 1px solid #bbb; margin-bottom:20px; }\n    h1 { float:left; margin: 0 10px 0 0; }\n    h1 a { display:block; height: 24px; }\n    h2 {font-size: 16px; line-height: 1.4em; color: #000; margin: 0;}\n\n    .container {background-color: #ddd; padding: 3px; width:450px; margin: 50px auto 20px auto; border-radius: 12px }\n    .content {background-color: #fff; border: 1px solid #aaa; padding: 30px; border-radius: 8px}\n\n    p {margin: 1em 0;}\n\n    ul { text-indent:0; margin: 1em 0 0 0; padding:0; list-style:none; }\n    ul li { margin: 0 0 .7em; font-size:130%; }\n\n\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="content">\n      <div id="header">\n        <h1>\n          <a href="http://www.getharvest.com/">\n            <svg xmlns="http://www.w3.org/2000/svg" width="128" height="24" viewBox="0 0 128 24">\n              <g fill="#E3682C" fill-rule="evenodd">\n                <path d="M0 23.07V.24h4.36v9.1h6.17V.25h4.36v22.83h-4.37V13.2H4.36v9.87H0M25.33 14.4h4.33L27.54 5.2h-.06l-2.15 9.23zm-6.23 8.67L24.76.24h5.6l5.5 22.83H31.7l-1.12-4.8h-6.04l-1.23 4.8h-4.2zm25.08-12.9h2.24c1.93 0 3.1-.95 3.1-3.16 0-2.2-1.17-3.15-3.1-3.15h-2.24v6.32zm5.88 12.9l-3.8-9.3h-2.08v9.3H39.8V.24h6.34c5.25 0 7.74 2.53 7.74 6.83 0 2.85-1 4.9-3.44 5.82l4.3 10.17h-4.68zM57.5.24h4.3l4 16.32h.07L69.85.24h4.27L68.3 23.07h-4.96L57.5.24M78.14 23.07V.24H90.1V4.1h-7.6v5.25h5.8v3.86h-5.8v6.02h7.9v3.85H78.15M101.96 3.6c-1.55 0-2.4.94-2.4 2.48 0 3.44 9.7 3.7 9.7 10.82 0 3.9-2.67 6.5-7.24 6.5-3.53 0-6.27-1.93-7.44-6.4l4.3-.92c.5 2.74 2.07 3.72 3.36 3.72 1.5 0 2.68-1 2.68-2.7 0-4.3-9.7-4.36-9.7-10.73 0-3.9 2.32-6.37 6.83-6.37 3.88 0 6.24 2.3 7 5.52l-3.9 1.13c-.73-2.14-1.68-3.06-3.2-3.06zM127.9.24V4.1h-5.08v18.97h-4.36V4.1h-5.1V.24h14.55"/>\n              </g>\n            </svg>\n          </a>\n        </h1>\n      </div>\n      <h2>We canʼt find the page youʼre looking for.</h2>\n\n      <p>\n        Sorry about that! The page you were looking for may have been moved or the address misspelled.\n      </p>\n\n      <ul>\n        <li id="market404">Go to the <a href="http://www.getharvest.com/">Harvest home page</a> or <a href="https://www.getharvest.com/contact">Contact Support</a></li>\n        <li id="account404" style="display:none;">Go to <a href="/" onClick="window.location = accounturl; return false;">Your Harvest Account</a> or <a href="https://www.getharvest.com/contact">Contact Support</a></li>\n      </ul>\n      <script>\n       <!--\n        url_test();\n       //-->\n      </script>\n    </div>\n  </div>\n</body>\n</html>\n`

**Comment by Yaaqoub** [comment]
@thetwosents Yes, I just tried it and it's true, I will fix it now.
Thank you for your report.

**Comment by thetwosents** [comment]
Thank you sooooo much! Such an awesome wrapper for the API!

**Comment by Yaaqoub** [comment]
@thetwosents i just forget to add a small '/' to the URL request. the same thing happened with projectUserAssignments.

but now the bug is fixed and I published the updates to npm
